name: Image Test Build Deploy

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: python -m pip install docker pytest fastapi six

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: .
          push: false
          tags: ghcr.io/ismael-su/python-ci:latest

      - name: Test Image
        run: pytest tests/image/

      - name: Push
        run: docker push ghcr.io/ismael-su/python-ci:latest

